import type { SoilTexture, SoilProperties, CropProperties, CropSoilPreference } from "./types";

// ═══════════════════════════════════════════════
//  BASE DE DATOS EDAFOLÓGICA — 8 TIPOS DE SUELO
// ═══════════════════════════════════════════════

export const SOIL_DATA: Record<SoilTexture, SoilProperties> = {
  Arenoso: {
    id: "Arenoso",
    name: "Arenoso",
    description: "Textura gruesa con predominio de arena (hasta 85%). Alta permeabilidad, baja retención hídrica y de nutrientes.",
    fieldCapacity: 12,
    wiltingPoint: 5,
    availableWater: 7,
    bulkDensity: 1.6,
    porosity: 38,
    cec: 5,
    organicMatterTypical: "0.5 – 1.0%",
    phTypical: [5.5, 6.5],
    drainage: "Rápido",
    suitabilitySummary: "Alta aireación y fácil laboreo, pero pobre fertilidad natural. Requiere riego frecuente y alto aporte de MO.",
    compactionRisk: 0.15,
    nutrientRetention: 0.15,
    rootPenetration: 0.9,
    aeration: 0.95,
  },
  "Franco-Arenoso": {
    id: "Franco-Arenoso",
    name: "Franco-Arenoso",
    description: "Textura moderadamente gruesa, mezcla equilibrada con predominio de arena. Buen drenaje.",
    fieldCapacity: 18,
    wiltingPoint: 8,
    availableWater: 10,
    bulkDensity: 1.5,
    porosity: 43,
    cec: 8,
    organicMatterTypical: "1.0 – 1.5%",
    phTypical: [5.5, 6.8],
    drainage: "Moderado",
    suitabilitySummary: "Aireado, fácil de trabajar. Responde bien a riego por goteo y fertilización orgánica fraccionada.",
    compactionRisk: 0.25,
    nutrientRetention: 0.3,
    rootPenetration: 0.85,
    aeration: 0.9,
  },
  Franco: {
    id: "Franco",
    name: "Franco",
    description: "Textura equilibrada (arena 40%, limo 40%, arcilla 20%). El estándar de referencia para la mayoría de cultivos.",
    fieldCapacity: 28,
    wiltingPoint: 12,
    availableWater: 16,
    bulkDensity: 1.35,
    porosity: 50,
    cec: 15,
    organicMatterTypical: "2.0 – 3.0%",
    phTypical: [6.0, 7.0],
    drainage: "Moderado",
    suitabilitySummary: "Ideal para la mayoría de cultivos. Excelente equilibrio entre retención de agua, aireación y fertilidad.",
    compactionRisk: 0.4,
    nutrientRetention: 0.6,
    rootPenetration: 0.8,
    aeration: 0.8,
  },
  "Franco-Limoso": {
    id: "Franco-Limoso",
    name: "Franco-Limoso",
    description: "Alto contenido de limo (50%+), textura suave y sedosa. Muy fértil pero susceptible a erosión hídrica.",
    fieldCapacity: 32,
    wiltingPoint: 13,
    availableWater: 19,
    bulkDensity: 1.3,
    porosity: 52,
    cec: 18,
    organicMatterTypical: "2.5 – 4.0%",
    phTypical: [6.0, 7.2],
    drainage: "Moderado",
    suitabilitySummary: "Muy buena fertilidad natural y retención de agua. Ideal para horticultura intensiva con cobertura vegetal.",
    compactionRisk: 0.5,
    nutrientRetention: 0.7,
    rootPenetration: 0.7,
    aeration: 0.7,
  },
  Limoso: {
    id: "Limoso",
    name: "Limoso",
    description: "Predominio de limo (80%+). Textura muy fina, alta fertilidad potencial pero propenso a compactación y encostramiento.",
    fieldCapacity: 34,
    wiltingPoint: 14,
    availableWater: 20,
    bulkDensity: 1.25,
    porosity: 55,
    cec: 20,
    organicMatterTypical: "3.0 – 5.0%",
    phTypical: [6.0, 7.5],
    drainage: "Lento",
    suitabilitySummary: "Alta fertilidad natural, excelente para pasturas y granos. Manejar con siembra directa y aportes de MO.",
    compactionRisk: 0.6,
    nutrientRetention: 0.75,
    rootPenetration: 0.6,
    aeration: 0.6,
  },
  "Franco-Arcilloso": {
    id: "Franco-Arcilloso",
    name: "Franco-Arcilloso",
    description: "Mezcla arcillo-limosa con 30-40% de arcilla. Buena fertilidad pero tendencia a compactarse.",
    fieldCapacity: 36,
    wiltingPoint: 18,
    availableWater: 18,
    bulkDensity: 1.3,
    porosity: 48,
    cec: 25,
    organicMatterTypical: "2.0 – 3.5%",
    phTypical: [5.5, 7.0],
    drainage: "Lento",
    suitabilitySummary: "Buena fertilidad química pero requiere manejo cuidadoso del agua para evitar anegamiento. Ideal para cultivos de raíz profunda.",
    compactionRisk: 0.65,
    nutrientRetention: 0.8,
    rootPenetration: 0.55,
    aeration: 0.55,
  },
  Arcilloso: {
    id: "Arcilloso",
    name: "Arcilloso",
    description: "Alto contenido de arcilla (45%+). Alta CIC pero pobre drenaje y aireación. Suelo 'frío' que tarda en calentarse.",
    fieldCapacity: 42,
    wiltingPoint: 22,
    availableWater: 20,
    bulkDensity: 1.2,
    porosity: 55,
    cec: 35,
    organicMatterTypical: "2.5 – 4.0%",
    phTypical: [5.5, 7.0],
    drainage: "Lento",
    suitabilitySummary: "Alta fertilidad potencial pero drenaje deficiente. Requiere camellones, drenajes o cultivos tolerantes al encharcamiento.",
    compactionRisk: 0.8,
    nutrientRetention: 0.9,
    rootPenetration: 0.35,
    aeration: 0.35,
  },
  Orgánico: {
    id: "Orgánico",
    name: "Orgánico (Histosol)",
    description: "Suelo con alto contenido de materia orgánica (>20%). Excelente retención de agua y nutrientes. Típico de humedales y zonas de acumulación de MO.",
    fieldCapacity: 55,
    wiltingPoint: 25,
    availableWater: 30,
    bulkDensity: 0.8,
    porosity: 70,
    cec: 40,
    organicMatterTypical: "15 – 30%",
    phTypical: [5.0, 6.5],
    drainage: "Lento",
    suitabilitySummary: "Excelente para horticultura orgánica y viveros si se maneja el drenaje. Alta biodiversidad microbiana. Requiere corrección de pH si es muy ácido.",
    compactionRisk: 0.7,
    nutrientRetention: 0.95,
    rootPenetration: 0.6,
    aeration: 0.6,
  },
};

// ════════════════════════════════════════════════════════
//  HELPERS PARA PREFERENCIAS DE SUELO POR CULTIVO
// ════════════════════════════════════════════════════════

function pref(
  texture: SoilTexture,
  suitability: number,
  notes: string,
): CropSoilPreference {
  return { texture, suitability, notes };
}

// ════════════════════════════════════════════════════════
//  BASE DE DATOS DE CULTIVOS — 26 ESPECIES
// ════════════════════════════════════════════════════════

export const CROP_DATA: CropProperties[] = [
  // =========================================
  //  CEREALES
  // =========================================
  {
    id: "maiz",
    name: "Maíz",
    scientificName: "Zea mays",
    family: "Poaceae",
    category: "Cereal",
    habit: "Anual",
    icon: "🌽",
    baseYield: 7500,
    maxYield: 11500,
    yieldUnit: "kg/ha",
    pricePerKg: 0.21,
    fixedCostPerHa: 500,
    kcInit: 0.3,
    kcMid: 1.2,
    kcEnd: 0.6,
    seasonDays: 140,
    idealIrrigationPct: 70,
    droughtTolerance: 0.35,
    waterloggingTolerance: 0.2,
    rootingDepth: "Profunda",
    nitrogenDemand: 150,
    phosphorusDemand: 60,
    potassiumDemand: 120,
    calciumDemand: 30,
    magnesiumDemand: 25,
    nitrogenFixer: false,
    idealPhMin: 5.8,
    idealPhMax: 7.2,
    saltTolerance: 0.3,
    soilPreferences: [
      pref("Franco", 1.0, "Textura ideal, excelente desarrollo radicular"),
      pref("Franco-Limoso", 0.95, "Muy buena fertilidad, alto potencial"),
      pref("Franco-Arcilloso", 0.85, "Buena retención de humedad"),
      pref("Limoso", 0.8, "Fértil pero requiere buen drenaje"),
      pref("Franco-Arenoso", 0.7, "Requiere riego frecuente y alta fertilización"),
      pref("Arcilloso", 0.5, "Riesgo de anegamiento en lluvias intensas"),
      pref("Arenoso", 0.35, "Pobre retención de agua y nutrientes"),
      pref("Orgánico", 0.45, "Alto potencial pero drenaje limitante"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 2200,
    baseTemperature: 10,
    frostTolerance: 0.1,
    goodCompanions: ["Poroto", "Zapallo", "Girasol"],
    badCompanions: ["Sorgo"],
    followCrops: ["Soja", "Trigo", "Avena"],
    pestResistance: 0.4,
    mycorrhizalDependency: 0.6,
    description: "Cereal fundamental para la seguridad alimentaria. Alta demanda de N y agua durante floración y llenado de grano.",
    agroecologicalNotes: "Asociar con poroto (milpa) reduce necesidad de N. Los residuos de cosecha aportan MO al suelo. El cultivo de cobertura de vicia antes del maíz puede aportar hasta 80 kg N/ha.",
  },
  {
    id: "trigo",
    name: "Trigo",
    scientificName: "Triticum aestivum",
    family: "Poaceae",
    category: "Cereal",
    habit: "Anual",
    icon: "🌾",
    baseYield: 3800,
    maxYield: 5500,
    yieldUnit: "kg/ha",
    pricePerKg: 0.25,
    fixedCostPerHa: 300,
    kcInit: 0.3,
    kcMid: 1.15,
    kcEnd: 0.4,
    seasonDays: 150,
    idealIrrigationPct: 45,
    droughtTolerance: 0.5,
    waterloggingTolerance: 0.4,
    rootingDepth: "Moderada",
    nitrogenDemand: 110,
    phosphorusDemand: 45,
    potassiumDemand: 80,
    calciumDemand: 20,
    magnesiumDemand: 18,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 7.5,
    saltTolerance: 0.5,
    soilPreferences: [
      pref("Franco-Limoso", 1.0, "Ideal: fértil y con buena retención de humedad"),
      pref("Franco", 0.95, "Excelente para trigo pan"),
      pref("Franco-Arcilloso", 0.85, "Buena fertilidad para el ciclo largo"),
      pref("Limoso", 0.85, "Alto potencial con manejo de drenaje"),
      pref("Franco-Arenoso", 0.6, "Requiere fertilización más fraccionada"),
      pref("Arcilloso", 0.55, "Puede retrasar la maduración"),
      pref("Arenoso", 0.3, "Pobre rendimiento, baja retención"),
      pref("Orgánico", 0.5, "Potencial alto si se corrige drenaje"),
    ],
    idealSeasons: ["Otoño-Invierno"],
    gddRequirement: 1800,
    baseTemperature: 5,
    frostTolerance: 0.7,
    goodCompanions: ["Arveja", "Vicia"],
    badCompanions: ["Cebada"],
    followCrops: ["Soja", "Girasol", "Maíz"],
    pestResistance: 0.3,
    mycorrhizalDependency: 0.5,
    description: "Cereal de invierno con buena tolerancia a heladas. Fundamental en rotaciones pampeanas.",
    agroecologicalNotes: "Antecesor vicia o arveja aporta N biológico. Ideal en rotación con soja. La siembra directa sobre rastrojo conserva la humedad del perfil.",
  },
  {
    id: "arroz",
    name: "Arroz",
    scientificName: "Oryza sativa",
    family: "Poaceae",
    category: "Cereal",
    habit: "Anual",
    icon: "🍚",
    baseYield: 5000,
    maxYield: 8000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.35,
    fixedCostPerHa: 700,
    kcInit: 1.05,
    kcMid: 1.2,
    kcEnd: 0.9,
    seasonDays: 130,
    idealIrrigationPct: 95,
    droughtTolerance: 0.1,
    waterloggingTolerance: 1.0,
    rootingDepth: "Superficial",
    nitrogenDemand: 120,
    phosphorusDemand: 50,
    potassiumDemand: 100,
    calciumDemand: 22,
    magnesiumDemand: 20,
    nitrogenFixer: false,
    idealPhMin: 5.0,
    idealPhMax: 7.0,
    saltTolerance: 0.4,
    soilPreferences: [
      pref("Arcilloso", 1.0, "Ideal para inundación controlada"),
      pref("Franco-Arcilloso", 0.9, "Buena retención de la lámina de agua"),
      pref("Franco-Limoso", 0.75, "Aceptable con control de percolación"),
      pref("Limoso", 0.7, "Requiere mayor control del agua"),
      pref("Franco", 0.5, "Requiere compactación para reducir infiltración"),
      pref("Orgánico", 0.8, "Alta fertilidad, buen comportamiento"),
      pref("Franco-Arenoso", 0.25, "Infiltración excesiva, no recomendado"),
      pref("Arenoso", 0.15, "No apto: pérdida de agua por percolación"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 2400,
    baseTemperature: 10,
    frostTolerance: 0.0,
    goodCompanions: ["Azolla"],
    badCompanions: [],
    followCrops: ["Trigo", "Soja", "Arveja"],
    pestResistance: 0.3,
    mycorrhizalDependency: 0.2,
    description: "Cereal acuático, principal fuente de calorías mundial. Cultivo en lámina de agua continua.",
    agroecologicalNotes: "El cultivo en fangueo convencional tiene alta huella hídrica y emite metano. Sistemas alternativos como arroz secano o SRI (System of Rice Intensification) reducen el consumo de agua 30-50%.",
  },
  {
    id: "sorgo",
    name: "Sorgo Granífero",
    scientificName: "Sorghum bicolor",
    family: "Poaceae",
    category: "Cereal",
    habit: "Anual",
    icon: "🌾",
    baseYield: 4500,
    maxYield: 7000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.18,
    fixedCostPerHa: 350,
    kcInit: 0.3,
    kcMid: 1.0,
    kcEnd: 0.55,
    seasonDays: 120,
    idealIrrigationPct: 50,
    droughtTolerance: 0.9,
    waterloggingTolerance: 0.2,
    rootingDepth: "Profunda",
    nitrogenDemand: 100,
    phosphorusDemand: 40,
    potassiumDemand: 85,
    calciumDemand: 18,
    magnesiumDemand: 20,
    nitrogenFixer: false,
    idealPhMin: 5.5,
    idealPhMax: 7.5,
    saltTolerance: 0.7,
    soilPreferences: [
      pref("Franco", 1.0, "Ideal para el cultivo"),
      pref("Franco-Arenoso", 0.9, "Buena adaptación por sistema radicular profundo"),
      pref("Franco-Limoso", 0.85, "Fértil, buen rendimiento"),
      pref("Franco-Arcilloso", 0.8, "Tolerante, buen potencial"),
      pref("Arenoso", 0.7, "Mejor que maíz en suelos livianos por tolerancia a sequía"),
      pref("Limoso", 0.75, "Potencial alto con manejo adecuado"),
      pref("Arcilloso", 0.5, "Tolerante pero sensible a anegamiento prolongado"),
      pref("Orgánico", 0.4, "No es su óptimo"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1800,
    baseTemperature: 10,
    frostTolerance: 0.1,
    goodCompanions: ["Poroto caupí"],
    badCompanions: ["Maíz"],
    followCrops: ["Soja", "Trigo", "Garbanzo"],
    pestResistance: 0.6,
    mycorrhizalDependency: 0.7,
    description: "Cereal de verano extremadamente tolerante a sequía. Sistema radicular que explora hasta 2 m de profundidad.",
    agroecologicalNotes: "Excelente para rotación en suelos arenosos donde el maíz rinde poco. Su rastrojo tiene relación C:N más alta que el maíz, ideal para cobertura. Muy eficiente en uso de agua (3.5 kg/m³).",
  },
  {
    id: "cebada",
    name: "Cebada",
    scientificName: "Hordeum vulgare",
    family: "Poaceae",
    category: "Cereal",
    habit: "Anual",
    icon: "🌾",
    baseYield: 3500,
    maxYield: 5200,
    yieldUnit: "kg/ha",
    pricePerKg: 0.22,
    fixedCostPerHa: 280,
    kcInit: 0.3,
    kcMid: 1.15,
    kcEnd: 0.25,
    seasonDays: 130,
    idealIrrigationPct: 40,
    droughtTolerance: 0.65,
    waterloggingTolerance: 0.3,
    rootingDepth: "Moderada",
    nitrogenDemand: 90,
    phosphorusDemand: 40,
    potassiumDemand: 70,
    calciumDemand: 15,
    magnesiumDemand: 15,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 7.5,
    saltTolerance: 0.7,
    soilPreferences: [
      pref("Franco", 1.0, "Ideal para maltería"),
      pref("Franco-Limoso", 0.95, "Excelente fertilidad"),
      pref("Franco-Arcilloso", 0.85, "Bueno, especialmente en ciclo largo"),
      pref("Franco-Arenoso", 0.65, "Aceptable si bien fertilizado"),
      pref("Limoso", 0.8, "Alto potencial"),
      pref("Arcilloso", 0.55, "Puede afectar calidad del grano"),
      pref("Arenoso", 0.35, "Baja retención, pobre rendimiento"),
      pref("Orgánico", 0.45, "Requiere manejo de N para calidad cervecera"),
    ],
    idealSeasons: ["Otoño-Invierno"],
    gddRequirement: 1600,
    baseTemperature: 5,
    frostTolerance: 0.75,
    goodCompanions: ["Arveja", "Lenteja"],
    badCompanions: ["Trigo"],
    followCrops: ["Soja", "Girasol", "Maíz"],
    pestResistance: 0.35,
    mycorrhizalDependency: 0.5,
    description: "Cereal de invierno usado para maltería y forraje. Más tolerante a suelos salinos que el trigo.",
    agroecologicalNotes: "La cebada es más tolerante a sales que el trigo, ideal para suelos con problemas de salinidad leve. En rotación, es un buen antecesor de soja por su ciclo más corto que permite adelantar la siembra.",
  },

  // =========================================
  //  OLEAGINOSAS
  // =========================================
  {
    id: "soja",
    name: "Soja",
    scientificName: "Glycine max",
    family: "Fabaceae",
    category: "Oleaginosa",
    habit: "Anual",
    icon: "🌱",
    baseYield: 3200,
    maxYield: 4800,
    yieldUnit: "kg/ha",
    pricePerKg: 0.42,
    fixedCostPerHa: 350,
    kcInit: 0.4,
    kcMid: 1.15,
    kcEnd: 0.5,
    seasonDays: 130,
    idealIrrigationPct: 50,
    droughtTolerance: 0.5,
    waterloggingTolerance: 0.3,
    rootingDepth: "Moderada",
    nitrogenDemand: 260,
    phosphorusDemand: 50,
    potassiumDemand: 110,
    calciumDemand: 25,
    magnesiumDemand: 22,
    nitrogenFixer: true,
    idealPhMin: 6.0,
    idealPhMax: 7.0,
    saltTolerance: 0.4,
    soilPreferences: [
      pref("Franco", 1.0, "Suelo óptimo para el cultivo"),
      pref("Franco-Limoso", 0.95, "Fértil, excelente potencial"),
      pref("Franco-Arcilloso", 0.85, "Buena retención de humedad"),
      pref("Limoso", 0.8, "Potencial alto con buen drenaje"),
      pref("Franco-Arenoso", 0.7, "Aceptable, requiere mayor fertilización"),
      pref("Arcilloso", 0.5, "Sensible a anegamiento temporario"),
      pref("Arenoso", 0.35, "Baja retención, estrés hídrico frecuente"),
      pref("Orgánico", 0.6, "Alto potencial orgánico, excelente simbiosis con rizobios"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 2000,
    baseTemperature: 10,
    frostTolerance: 0.1,
    goodCompanions: ["Maíz"],
    badCompanions: ["Girasol"],
    followCrops: ["Trigo", "Maíz", "Avena"],
    pestResistance: 0.3,
    mycorrhizalDependency: 0.5,
    description: "Oleaginosa de verano, principal cultivo de Argentina. Fija N₂ atmosférico en simbiosis con Bradyrhizobium japonicum.",
    agroecologicalNotes: "La fijación biológica puede aportar 150-250 kg N/ha/año si la inoculación es efectiva. El exceso de N sintético (>60 kg/ha) inhibe la nodulación. Ideal en rotación con maíz (que aprovecha el N residual).",
  },
  {
    id: "girasol",
    name: "Girasol",
    scientificName: "Helianthus annuus",
    family: "Asteraceae",
    category: "Oleaginosa",
    habit: "Anual",
    icon: "🌻",
    baseYield: 2500,
    maxYield: 4000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.48,
    fixedCostPerHa: 320,
    kcInit: 0.35,
    kcMid: 1.1,
    kcEnd: 0.35,
    seasonDays: 125,
    idealIrrigationPct: 45,
    droughtTolerance: 0.85,
    waterloggingTolerance: 0.3,
    rootingDepth: "Profunda",
    nitrogenDemand: 100,
    phosphorusDemand: 45,
    potassiumDemand: 140,
    calciumDemand: 20,
    magnesiumDemand: 18,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 7.5,
    saltTolerance: 0.65,
    soilPreferences: [
      pref("Franco", 1.0, "Ideal: drenaje y fertilidad óptimos"),
      pref("Franco-Arenoso", 0.9, "Buena adaptación por raíz pivotante profunda"),
      pref("Franco-Limoso", 0.9, "Excelente fertilidad"),
      pref("Franco-Arcilloso", 0.8, "Buen potencial productivo"),
      pref("Limoso", 0.75, "Potencial alto"),
      pref("Arenoso", 0.65, "Tolera mejor que otros cultivos extensivos"),
      pref("Arcilloso", 0.5, "Tolerante si no hay excesos hídricos"),
      pref("Orgánico", 0.55, "Comportamiento aceptable"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1900,
    baseTemperature: 8,
    frostTolerance: 0.3,
    goodCompanions: ["Maíz", "Poroto"],
    badCompanions: ["Soja", "Girasol (monocultivo)"],
    followCrops: ["Trigo", "Cebada", "Avena"],
    pestResistance: 0.5,
    mycorrhizalDependency: 0.6,
    description: "Oleaginosa de verano con sistema radicular pivotante que explora horizontes profundos. Tolerante a sequía y suelos marginales.",
    agroecologicalNotes: "Excelente cultivo para rotación por su raíz pivotante que descompacta el suelo. Sus residuos se descomponen más lentamente, aportando MO estable. Tolera mejor que la soja los suelos con problemas de drenaje.",
  },

  // =========================================
  //  LEGUMBRES
  // =========================================
  {
    id: "poroto",
    name: "Poroto",
    scientificName: "Phaseolus vulgaris",
    family: "Fabaceae",
    category: "Legumbre",
    habit: "Anual",
    icon: "🫘",
    baseYield: 1800,
    maxYield: 3000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.85,
    fixedCostPerHa: 400,
    kcInit: 0.4,
    kcMid: 1.05,
    kcEnd: 0.9,
    seasonDays: 90,
    idealIrrigationPct: 55,
    droughtTolerance: 0.3,
    waterloggingTolerance: 0.2,
    rootingDepth: "Superficial",
    nitrogenDemand: 80,
    phosphorusDemand: 35,
    potassiumDemand: 60,
    calciumDemand: 18,
    magnesiumDemand: 15,
    nitrogenFixer: true,
    idealPhMin: 6.0,
    idealPhMax: 7.0,
    saltTolerance: 0.3,
    soilPreferences: [
      pref("Franco", 1.0, "Óptimo para el desarrollo del cultivo"),
      pref("Franco-Limoso", 0.95, "Excelente fertilidad"),
      pref("Franco-Arenoso", 0.85, "Aireación ideal para raíces superficiales"),
      pref("Franco-Arcilloso", 0.7, "Buena fertilidad pero riesgo de asfixia radicular"),
      pref("Limoso", 0.75, "Potencial alto con buen drenaje"),
      pref("Arenoso", 0.65, "Aceptable con riego frecuente"),
      pref("Arcilloso", 0.35, "Muy sensible a encharcamiento"),
      pref("Orgánico", 0.7, "Excelente asociación con rizobios en suelos orgánicos"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1400,
    baseTemperature: 10,
    frostTolerance: 0.0,
    goodCompanions: ["Maíz", "Zapallo", "Frutilla"],
    badCompanions: ["Cebolla", "Ajo"],
    followCrops: ["Maíz", "Trigo", "Lechuga"],
    pestResistance: 0.3,
    mycorrhizalDependency: 0.6,
    description: "Legumbre de grano, rica en proteínas. Raíz superficial, sensible al estrés hídrico. Fija N₂ en simbiosis con Rhizobium phaseoli.",
    agroecologicalNotes: "Tres hermanas (maíz + poroto + zapallo) es el sistema agroecológico más antiguo de América. El poroto trepador sobre maíz optimiza el uso del espacio vertical.",
  },
  {
    id: "arveja",
    name: "Arveja",
    scientificName: "Pisum sativum",
    family: "Fabaceae",
    category: "Legumbre",
    habit: "Anual",
    icon: "🫛",
    baseYield: 2500,
    maxYield: 3800,
    yieldUnit: "kg/ha",
    pricePerKg: 0.6,
    fixedCostPerHa: 350,
    kcInit: 0.4,
    kcMid: 1.15,
    kcEnd: 0.3,
    seasonDays: 100,
    idealIrrigationPct: 50,
    droughtTolerance: 0.4,
    waterloggingTolerance: 0.2,
    rootingDepth: "Moderada",
    nitrogenDemand: 60,
    phosphorusDemand: 30,
    potassiumDemand: 55,
    calciumDemand: 15,
    magnesiumDemand: 12,
    nitrogenFixer: true,
    idealPhMin: 5.8,
    idealPhMax: 7.0,
    saltTolerance: 0.35,
    soilPreferences: [
      pref("Franco", 1.0, "Condiciones ideales"),
      pref("Franco-Limoso", 0.95, "Fértil, excelente desarrollo"),
      pref("Franco-Arenoso", 0.85, "Buena aireación radicular"),
      pref("Limoso", 0.8, "Alto potencial"),
      pref("Franco-Arcilloso", 0.7, "Aceptable con buen drenaje"),
      pref("Arenoso", 0.6, "Requiere riego y fertilización"),
      pref("Arcilloso", 0.35, "Sensible a excesos hídricos"),
      pref("Orgánico", 0.7, "Alta respuesta a condiciones orgánicas"),
    ],
    idealSeasons: ["Otoño-Invierno"],
    gddRequirement: 1300,
    baseTemperature: 5,
    frostTolerance: 0.65,
    goodCompanions: ["Lechuga", "Zanahoria", "Rábano"],
    badCompanions: ["Cebolla", "Ajo"],
    followCrops: ["Maíz", "Lechuga", "Papa"],
    pestResistance: 0.35,
    mycorrhizalDependency: 0.5,
    description: "Legumbre de invierno, excelente antecesor por su aporte de N. Grano rico en proteínas.",
    agroecologicalNotes: "Excelente cultivo de cobertura en invierno. Aporta 40-60 kg N/ha al suelo. Su ciclo corto permite doble cultivo. El rastrojo se descompone rápido liberando N rápidamente.",
  },
  {
    id: "garbanzo",
    name: "Garbanzo",
    scientificName: "Cicer arietinum",
    family: "Fabaceae",
    category: "Legumbre",
    habit: "Anual",
    icon: "🫘",
    baseYield: 1500,
    maxYield: 2500,
    yieldUnit: "kg/ha",
    pricePerKg: 1.1,
    fixedCostPerHa: 380,
    kcInit: 0.4,
    kcMid: 1.0,
    kcEnd: 0.35,
    seasonDays: 110,
    idealIrrigationPct: 40,
    droughtTolerance: 0.75,
    waterloggingTolerance: 0.15,
    rootingDepth: "Profunda",
    nitrogenDemand: 50,
    phosphorusDemand: 30,
    potassiumDemand: 65,
    calciumDemand: 20,
    magnesiumDemand: 14,
    nitrogenFixer: true,
    idealPhMin: 6.0,
    idealPhMax: 8.0,
    saltTolerance: 0.5,
    soilPreferences: [
      pref("Franco", 1.0, "Óptimo para el cultivo"),
      pref("Franco-Arenoso", 0.9, "Excelente drenaje, buena adaptación"),
      pref("Franco-Limoso", 0.85, "Fértil, buen potencial"),
      pref("Arenoso", 0.8, "Suelos livianos favorecen el desarrollo"),
      pref("Franco-Arcilloso", 0.65, "Requiere buen drenaje"),
      pref("Limoso", 0.7, "Potencial medio"),
      pref("Arcilloso", 0.3, "Muy sensible a excesos de humedad"),
      pref("Orgánico", 0.5, "Comportamiento aceptable"),
    ],
    idealSeasons: ["Otoño-Invierno"],
    gddRequirement: 1600,
    baseTemperature: 5,
    frostTolerance: 0.5,
    goodCompanions: ["Sorgo", "Cebada"],
    badCompanions: ["Soja"],
    followCrops: ["Maíz", "Girasol", "Sorgo"],
    pestResistance: 0.4,
    mycorrhizalDependency: 0.5,
    description: "Legumbre de invierno tolerante a sequía. Raíz pivotante que explora horizontes profundos.",
    agroecologicalNotes: "Ideal para secano en suelos arenosos. Fija N₂ con Mesorhizobium ciceri. En rotación, aporta N para el cultivo de maíz siguiente.",
  },

  // =========================================
  //  HORTÍCOLAS
  // =========================================
  {
    id: "tomate",
    name: "Tomate",
    scientificName: "Solanum lycopersicum",
    family: "Solanaceae",
    category: "Hortícola",
    habit: "Anual",
    icon: "🍅",
    baseYield: 40000,
    maxYield: 65000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.65,
    fixedCostPerHa: 1500,
    kcInit: 0.6,
    kcMid: 1.15,
    kcEnd: 0.8,
    seasonDays: 120,
    idealIrrigationPct: 80,
    droughtTolerance: 0.25,
    waterloggingTolerance: 0.2,
    rootingDepth: "Profunda",
    nitrogenDemand: 180,
    phosphorusDemand: 80,
    potassiumDemand: 250,
    calciumDemand: 60,
    magnesiumDemand: 30,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 6.8,
    saltTolerance: 0.4,
    soilPreferences: [
      pref("Franco", 1.0, "Ideal para tomate platense"),
      pref("Franco-Limoso", 0.95, "Muy fértil, alto potencial"),
      pref("Franco-Arenoso", 0.85, "Aireado, buen desarrollo radicular inicial"),
      pref("Franco-Arcilloso", 0.75, "Buena retención, riesgo de Phytophthora"),
      pref("Limoso", 0.7, "Fértil, requiere monitoreo de enfermedades"),
      pref("Orgánico", 0.9, "Excelente respuesta en sistemas orgánicos"),
      pref("Arenoso", 0.55, "Requiere fertirriego constante"),
      pref("Arcilloso", 0.4, "Alto riesgo de enfermedades de raíz"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 2000,
    baseTemperature: 12,
    frostTolerance: 0.0,
    goodCompanions: ["Albahaca", "Cebolla", "Zanahoria"],
    badCompanions: ["Papa", "Pimiento", "Berenjena"],
    followCrops: ["Lechuga", "Poroto", "Zanahoria"],
    pestResistance: 0.25,
    mycorrhizalDependency: 0.7,
    description: "Hortícola de fruto de alto valor. Requiere tutoreo y poda. Muy exigente en K y Ca.",
    agroecologicalNotes: "La asociación con albahaca repele trips y mosca blanca. El acolchado plástico o mulch orgánico conserva humedad y reduce malezas. El compost aporta K y mejora la sanidad.",
  },
  {
    id: "papa",
    name: "Papa",
    scientificName: "Solanum tuberosum",
    family: "Solanaceae",
    category: "Hortícola",
    habit: "Anual",
    icon: "🥔",
    baseYield: 25000,
    maxYield: 40000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.25,
    fixedCostPerHa: 1200,
    kcInit: 0.5,
    kcMid: 1.15,
    kcEnd: 0.75,
    seasonDays: 110,
    idealIrrigationPct: 70,
    droughtTolerance: 0.3,
    waterloggingTolerance: 0.15,
    rootingDepth: "Superficial",
    nitrogenDemand: 130,
    phosphorusDemand: 100,
    potassiumDemand: 220,
    calciumDemand: 30,
    magnesiumDemand: 25,
    nitrogenFixer: false,
    idealPhMin: 5.2,
    idealPhMax: 6.5,
    saltTolerance: 0.3,
    soilPreferences: [
      pref("Franco-Arenoso", 1.0, "Suelo ideal: suelto, aireado, facilita tuberización"),
      pref("Arenoso", 0.95, "Excelente para formación de tubérculos"),
      pref("Franco", 0.9, "Bueno, pero puede compactarse"),
      pref("Franco-Limoso", 0.75, "Aceptable, riesgo de sarna común si pH sube"),
      pref("Limoso", 0.6, "Se compacta fácilmente, perjudica la tuberización"),
      pref("Franco-Arcilloso", 0.5, "Riesgo de asfixia y enfermedades"),
      pref("Orgánico", 0.85, "Excelente respuesta orgánica en suelos sueltos"),
      pref("Arcilloso", 0.3, "No recomendado: deformación de tubérculos"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1600,
    baseTemperature: 7,
    frostTolerance: 0.15,
    goodCompanions: ["Poroto", "Maíz", "Repollo"],
    badCompanions: ["Tomate", "Pimiento", "Berenjena"],
    followCrops: ["Trigo", "Avena", "Arveja"],
    pestResistance: 0.2,
    mycorrhizalDependency: 0.7,
    description: "Tubérculo fundamental para la seguridad alimentaria. Muy sensible a compactación y enfermedades del suelo.",
    agroecologicalNotes: "Requiere suelo suelto y bien aireado. El cultivo en camellones mejora el drenaje. No repetir en el mismo lote por 3-4 años por enfermedades del suelo. El compost maduro reduce la incidencia de sarna común.",
  },
  {
    id: "lechuga",
    name: "Lechuga",
    scientificName: "Lactuca sativa",
    family: "Asteraceae",
    category: "Hortícola",
    habit: "Anual",
    icon: "🥬",
    baseYield: 25000,
    maxYield: 35000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.5,
    fixedCostPerHa: 800,
    kcInit: 0.5,
    kcMid: 1.0,
    kcEnd: 0.95,
    seasonDays: 60,
    idealIrrigationPct: 65,
    droughtTolerance: 0.2,
    waterloggingTolerance: 0.25,
    rootingDepth: "Superficial",
    nitrogenDemand: 80,
    phosphorusDemand: 35,
    potassiumDemand: 140,
    calciumDemand: 40,
    magnesiumDemand: 15,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 7.0,
    saltTolerance: 0.35,
    soilPreferences: [
      pref("Franco", 1.0, "Textura ideal para el cultivo"),
      pref("Franco-Limoso", 0.95, "Fértil, buen crecimiento"),
      pref("Franco-Arenoso", 0.9, "Ciclo más rápido, buen drenaje"),
      pref("Orgánico", 0.95, "Excelente en suelos orgánicos"),
      pref("Limoso", 0.8, "Potencial alto"),
      pref("Franco-Arcilloso", 0.65, "Aceptable, riesgo de pudrición"),
      pref("Arenoso", 0.7, "Buena con riego frecuente"),
      pref("Arcilloso", 0.35, "No recomendado"),
    ],
    idealSeasons: ["Todo el año"],
    gddRequirement: 800,
    baseTemperature: 5,
    frostTolerance: 0.4,
    goodCompanions: ["Zanahoria", "Rábano", "Cebolla"],
    badCompanions: ["Perejil", "Apio"],
    followCrops: ["Poroto", "Tomate", "Pimiento"],
    pestResistance: 0.3,
    mycorrhizalDependency: 0.4,
    description: "Hortaliza de hoja de hoja de ciclo corto. Raíz superficial, sensible a estrés hídrico. Alta demanda de K.",
    agroecologicalNotes: "Ciclo corto ideal para rotaciones intensivas. El mulch orgánico mantiene la humedad y evita salpicaduras que transmiten hongos. Asociar con zanahoria optimiza el uso del espacio radicular.",
  },
  {
    id: "cebolla",
    name: "Cebolla",
    scientificName: "Allium cepa",
    family: "Amaryllidaceae",
    category: "Hortícola",
    habit: "Bianual",
    icon: "🧅",
    baseYield: 30000,
    maxYield: 45000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.3,
    fixedCostPerHa: 900,
    kcInit: 0.7,
    kcMid: 1.05,
    kcEnd: 0.75,
    seasonDays: 140,
    idealIrrigationPct: 60,
    droughtTolerance: 0.35,
    waterloggingTolerance: 0.15,
    rootingDepth: "Superficial",
    nitrogenDemand: 90,
    phosphorusDemand: 40,
    potassiumDemand: 130,
    calciumDemand: 30,
    magnesiumDemand: 16,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 7.0,
    saltTolerance: 0.4,
    soilPreferences: [
      pref("Franco-Arenoso", 1.0, "Ideal: suelto para el bulbeo"),
      pref("Arenoso", 0.95, "Excelente para formación de bulbos"),
      pref("Franco", 0.9, "Buen desarrollo, textura equilibrada"),
      pref("Franco-Limoso", 0.85, "Fértil, buen potencial"),
      pref("Orgánico", 0.8, "Buena respuesta a suelos orgánicos"),
      pref("Limoso", 0.65, "Aceptable, riesgo de compactación"),
      pref("Franco-Arcilloso", 0.5, "Puede dificultar el bulbeo"),
      pref("Arcilloso", 0.3, "No recomendado para bulbeo"),
    ],
    idealSeasons: ["Otoño-Invierno", "Primavera-Verano"],
    gddRequirement: 1800,
    baseTemperature: 5,
    frostTolerance: 0.5,
    goodCompanions: ["Zanahoria", "Lechuga", "Remolacha"],
    badCompanions: ["Poroto", "Arveja"],
    followCrops: ["Lechuga", "Tomate", "Papa"],
    pestResistance: 0.35,
    mycorrhizalDependency: 0.3,
    description: "Hortaliza de bulbo, ciclo largo. Muy sensible a la competencia de malezas. Requiere suelo suelto para el engrosamiento del bulbo.",
    agroecologicalNotes: "La asociación con zanahoria repele mutuamente plagas (mosca de la cebolla y mosca de la zanahoria). El cultivo en camellón mejora el drenaje y el bulbeo.",
  },
  {
    id: "frutilla",
    name: "Frutilla",
    scientificName: "Fragaria × ananassa",
    family: "Rosaceae",
    category: "Hortícola",
    habit: "Perenne",
    icon: "🍓",
    baseYield: 25000,
    maxYield: 40000,
    yieldUnit: "kg/ha",
    pricePerKg: 2.5,
    fixedCostPerHa: 3000,
    kcInit: 0.4,
    kcMid: 0.85,
    kcEnd: 0.7,
    seasonDays: 200,
    idealIrrigationPct: 75,
    droughtTolerance: 0.2,
    waterloggingTolerance: 0.15,
    rootingDepth: "Superficial",
    nitrogenDemand: 110,
    phosphorusDemand: 50,
    potassiumDemand: 180,
    calciumDemand: 35,
    magnesiumDemand: 22,
    nitrogenFixer: false,
    idealPhMin: 5.5,
    idealPhMax: 6.5,
    saltTolerance: 0.3,
    soilPreferences: [
      pref("Franco-Arenoso", 1.0, "Ideal para macrotúnel, suelto y drenante"),
      pref("Franco", 0.95, "Excelente, equilibrado"),
      pref("Arenoso", 0.85, "Buen drenaje, requiere fertirriego"),
      pref("Franco-Limoso", 0.8, "Fértil, monitorear drenaje"),
      pref("Orgánico", 0.95, "Excelente para producción orgánica"),
      pref("Limoso", 0.6, "Riesgo de Botrytis si no hay buen drenaje"),
      pref("Franco-Arcilloso", 0.5, "Mayor riesgo de enfermedades radiculares"),
      pref("Arcilloso", 0.25, "No apto: asfixia radicular"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1400,
    baseTemperature: 5,
    frostTolerance: 0.2,
    goodCompanions: ["Lechuga", "Poroto", "Espinaca"],
    badCompanions: ["Papa", "Tomate", "Pimiento"],
    followCrops: ["Lechuga", "Poroto", "Avena"],
    pestResistance: 0.2,
    mycorrhizalDependency: 0.7,
    description: "Fruto rojo de alto valor comercial. Se cultiva en macrotúnel o a campo con acolchado plástico.",
    agroecologicalNotes: "El acolchado con paja (mulch orgánico) reduce la incidencia de Botrytis y conserva humedad. Los hongos micorrícicos mejoran la absorción de P y la resistencia a estrés.",
  },
  {
    id: "zapallo",
    name: "Zapallo (Anco)",
    scientificName: "Cucurbita moschata",
    family: "Cucurbitaceae",
    category: "Hortícola",
    habit: "Anual",
    icon: "🎃",
    baseYield: 20000,
    maxYield: 35000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.35,
    fixedCostPerHa: 600,
    kcInit: 0.5,
    kcMid: 1.0,
    kcEnd: 0.8,
    seasonDays: 140,
    idealIrrigationPct: 60,
    droughtTolerance: 0.55,
    waterloggingTolerance: 0.3,
    rootingDepth: "Profunda",
    nitrogenDemand: 100,
    phosphorusDemand: 55,
    potassiumDemand: 160,
    calciumDemand: 45,
    magnesiumDemand: 25,
    nitrogenFixer: false,
    idealPhMin: 5.8,
    idealPhMax: 7.2,
    saltTolerance: 0.4,
    soilPreferences: [
      pref("Franco", 1.0, "Óptimo para el cultivo"),
      pref("Franco-Limoso", 0.95, "Fértil, alto potencial"),
      pref("Franco-Arenoso", 0.85, "Buen desarrollo radicular"),
      pref("Franco-Arcilloso", 0.75, "Buena retención de humedad"),
      pref("Limoso", 0.7, "Potencial alto"),
      pref("Orgánico", 0.8, "Alta respuesta orgánica"),
      pref("Arenoso", 0.6, "Requiere riego"),
      pref("Arcilloso", 0.4, "Sensible a encharcamiento"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1800,
    baseTemperature: 12,
    frostTolerance: 0.0,
    goodCompanions: ["Maíz", "Poroto", "Girasol"],
    badCompanions: ["Papa"],
    followCrops: ["Trigo", "Maíz", "Arveja"],
    pestResistance: 0.4,
    mycorrhizalDependency: 0.6,
    description: "Cucurbitácea de fruto estival. Parte del sistema tradicional de las Tres Hermanas.",
    agroecologicalNotes: "Componente del sistema milpa (maíz + poroto + zapallo). El zapallo cubre el suelo reduciendo malezas y la evapotranspiración. Sus hojas anchas proporcionan sombra que conserva la humedad.",
  },

  // =========================================
  //  FORRAJERAS
  // =========================================
  {
    id: "alfalfa",
    name: "Alfalfa",
    scientificName: "Medicago sativa",
    family: "Fabaceae",
    category: "Forrajera",
    habit: "Perenne",
    icon: "☘️",
    baseYield: 12000,
    maxYield: 18000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.12,
    fixedCostPerHa: 280,
    kcInit: 0.4,
    kcMid: 0.95,
    kcEnd: 0.9,
    seasonDays: 365,
    idealIrrigationPct: 65,
    droughtTolerance: 0.7,
    waterloggingTolerance: 0.1,
    rootingDepth: "Profunda",
    nitrogenDemand: 30,
    phosphorusDemand: 50,
    potassiumDemand: 180,
    calciumDemand: 70,
    magnesiumDemand: 25,
    nitrogenFixer: true,
    idealPhMin: 6.5,
    idealPhMax: 7.5,
    saltTolerance: 0.5,
    soilPreferences: [
      pref("Franco", 1.0, "Óptimo: profundo, fértil, bien drenado"),
      pref("Franco-Limoso", 0.95, "Muy fértil, excelente productividad"),
      pref("Franco-Arcilloso", 0.85, "Buena retención de humedad, raíz profunda"),
      pref("Limoso", 0.8, "Alto potencial, requiere control de malezas"),
      pref("Franco-Arenoso", 0.7, "Aceptable con riego"),
      pref("Arcilloso", 0.45, "Sensible a encharcamiento prolongado"),
      pref("Arenoso", 0.35, "Baja retención, pobre performance"),
      pref("Orgánico", 0.75, "Buena simbiosis con Sinorhizobium meliloti"),
    ],
    idealSeasons: ["Todo el año"],
    gddRequirement: 800,
    baseTemperature: 5,
    frostTolerance: 0.6,
    goodCompanions: ["Festuca", "Cebadilla"],
    badCompanions: [],
    followCrops: ["Maíz", "Trigo", "Girasol"],
    pestResistance: 0.4,
    mycorrhizalDependency: 0.5,
    description: "Forrajera perenne de alta calidad proteica. Raíz pivotante que puede alcanzar 5 m de profundidad. Fija N₂ con Sinorhizobium meliloti.",
    agroecologicalNotes: "La alfalfa es clave en rotaciones orgánicas por su fijación de N (200-300 kg N/ha/año) y su capacidad de descompactar el suelo. Ideal para sistemas silvopastoriles con algarrobos.",
  },
  {
    id: "avena",
    name: "Avena",
    scientificName: "Avena sativa",
    family: "Poaceae",
    category: "Forrajera",
    habit: "Anual",
    icon: "🌾",
    baseYield: 3500,
    maxYield: 5000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.2,
    fixedCostPerHa: 250,
    kcInit: 0.3,
    kcMid: 1.15,
    kcEnd: 0.25,
    seasonDays: 110,
    idealIrrigationPct: 45,
    droughtTolerance: 0.6,
    waterloggingTolerance: 0.5,
    rootingDepth: "Moderada",
    nitrogenDemand: 70,
    phosphorusDemand: 30,
    potassiumDemand: 60,
    calciumDemand: 12,
    magnesiumDemand: 12,
    nitrogenFixer: false,
    idealPhMin: 5.5,
    idealPhMax: 7.0,
    saltTolerance: 0.5,
    soilPreferences: [
      pref("Franco", 1.0, "Ideal para grano o forraje"),
      pref("Franco-Limoso", 0.95, "Fértil, buena productividad"),
      pref("Franco-Arcilloso", 0.85, "Tolerante, buen ciclo"),
      pref("Limoso", 0.85, "Alto potencial forrajero"),
      pref("Franco-Arenoso", 0.7, "Aceptable"),
      pref("Arcilloso", 0.6, "Tolerante a excesos temporarios"),
      pref("Arenoso", 0.4, "Baja productividad"),
      pref("Orgánico", 0.65, "Buena respuesta"),
    ],
    idealSeasons: ["Otoño-Invierno"],
    gddRequirement: 1400,
    baseTemperature: 5,
    frostTolerance: 0.7,
    goodCompanions: ["Arveja", "Vicia"],
    badCompanions: [],
    followCrops: ["Maíz", "Soja", "Girasol"],
    pestResistance: 0.45,
    mycorrhizalDependency: 0.5,
    description: "Cereal de invierno multipropósito: grano, forraje, cobertura verde. Excelente como cultivo de servicio.",
    agroecologicalNotes: "Excelente como cobertura invernal. La avena + vicia es el cultivo de servicio más usado en Argentina agroecológico. Aporta biomasa, protege el suelo y recicla nutrientes. Fácil de secar con rolo.",
  },

  // =========================================
  //  FRUTALES
  // =========================================
  {
    id: "vid",
    name: "Vid (Uva de Vino)",
    scientificName: "Vitis vinifera",
    family: "Vitaceae",
    category: "Frutal",
    habit: "Perenne",
    icon: "🍇",
    baseYield: 8000,
    maxYield: 14000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.7,
    fixedCostPerHa: 2500,
    kcInit: 0.5,
    kcMid: 0.7,
    kcEnd: 0.45,
    seasonDays: 180,
    idealIrrigationPct: 50,
    droughtTolerance: 0.7,
    waterloggingTolerance: 0.1,
    rootingDepth: "Profunda",
    nitrogenDemand: 60,
    phosphorusDemand: 30,
    potassiumDemand: 90,
    calciumDemand: 50,
    magnesiumDemand: 15,
    nitrogenFixer: false,
    idealPhMin: 5.5,
    idealPhMax: 7.0,
    saltTolerance: 0.35,
    soilPreferences: [
      pref("Franco-Arenoso", 1.0, "Ideal para uva de vino de calidad"),
      pref("Franco", 0.95, "Excelente para producción"),
      pref("Arenoso", 0.9, "Suelos pobres mejoran la calidad enológica"),
      pref("Franco-Arcilloso", 0.75, "Más vigor, más rendimiento, menor calidad"),
      pref("Franco-Limoso", 0.8, "Fértil, buen desarrollo"),
      pref("Limoso", 0.65, "Riesgo de exceso de vigor"),
      pref("Arcilloso", 0.4, "Mala aireación, pudrición radicular"),
      pref("Orgánico", 0.6, "Alta fertilidad, controlar vigor"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 2000,
    baseTemperature: 10,
    frostTolerance: 0.2,
    goodCompanions: ["Romero", "Lavanda", "Mostaza"],
    badCompanions: ["Nogal"],
    followCrops: [],
    pestResistance: 0.25,
    mycorrhizalDependency: 0.7,
    description: "Frutal perenne, base de la vitivinicultura. Los suelos pobres y bien drenados producen vinos de mayor calidad.",
    agroecologicalNotes: "La vid es muy sensible a la compactación. Las cubiertas vegetales entre hileras (gramíneas o leguminosas) controlan la erosión y mejoran la estructura del suelo. El compost aporta MO y mejora la actividad biológica.",
  },
  {
    id: "manzano",
    name: "Manzano",
    scientificName: "Malus domestica",
    family: "Rosaceae",
    category: "Frutal",
    habit: "Perenne",
    icon: "🍎",
    baseYield: 25000,
    maxYield: 40000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.5,
    fixedCostPerHa: 3500,
    kcInit: 0.5,
    kcMid: 1.15,
    kcEnd: 0.7,
    seasonDays: 200,
    idealIrrigationPct: 70,
    droughtTolerance: 0.3,
    waterloggingTolerance: 0.1,
    rootingDepth: "Moderada",
    nitrogenDemand: 80,
    phosphorusDemand: 35,
    potassiumDemand: 140,
    calciumDemand: 60,
    magnesiumDemand: 20,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 7.0,
    saltTolerance: 0.3,
    soilPreferences: [
      pref("Franco", 1.0, "Óptimo para el desarrollo del cultivo"),
      pref("Franco-Limoso", 0.95, "Fértil, buena producción"),
      pref("Franco-Arcilloso", 0.8, "Aceptable con portainjerto MM106"),
      pref("Franco-Arenoso", 0.75, "Requiere riego, fruta de buena calidad"),
      pref("Limoso", 0.7, "Potencial medio-alto"),
      pref("Arcilloso", 0.4, "Riesgo de asfixia radicular y Phytophthora"),
      pref("Arenoso", 0.4, "Baja retención, estrés frecuente"),
      pref("Orgánico", 0.75, "Alta calidad de fruta en sistemas orgánicos"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 2200,
    baseTemperature: 7,
    frostTolerance: 0.35,
    goodCompanions: ["Ajo", "Capuchina", "Eneldo"],
    badCompanions: ["Nogal"],
    followCrops: [],
    pestResistance: 0.2,
    mycorrhizalDependency: 0.6,
    description: "Frutal de pepita de zonas templadas. Requiere horas de frío invernal para romper dormición.",
    agroecologicalNotes: "Los portainjertos enanizantes (M9) permiten mayor densidad y facilitan el manejo. El acolchado orgánico bajo la copa conserva humedad y aporta N. Las cubiertas de trébol en las calles fijan N y albergan controladores biológicos.",
  },

  // =========================================
  //  INDUSTRIALES
  // =========================================
  {
    id: "algodon",
    name: "Algodón",
    scientificName: "Gossypium hirsutum",
    family: "Malvaceae",
    category: "Industrial",
    habit: "Anual",
    icon: "🌿",
    baseYield: 2800,
    maxYield: 4500,
    yieldUnit: "kg/ha",
    pricePerKg: 1.2,
    fixedCostPerHa: 900,
    kcInit: 0.4,
    kcMid: 1.15,
    kcEnd: 0.7,
    seasonDays: 160,
    idealIrrigationPct: 65,
    droughtTolerance: 0.7,
    waterloggingTolerance: 0.2,
    rootingDepth: "Profunda",
    nitrogenDemand: 130,
    phosphorusDemand: 50,
    potassiumDemand: 100,
    calciumDemand: 40,
    magnesiumDemand: 25,
    nitrogenFixer: false,
    idealPhMin: 5.8,
    idealPhMax: 7.5,
    saltTolerance: 0.6,
    soilPreferences: [
      pref("Franco", 1.0, "Óptimo: textura equilibrada"),
      pref("Franco-Arcilloso", 0.9, "Buena retención, raíz profunda"),
      pref("Franco-Limoso", 0.9, "Fértil, alto potencial"),
      pref("Limoso", 0.8, "Potencial alto"),
      pref("Franco-Arenoso", 0.75, "Aceptable con riego"),
      pref("Arcilloso", 0.6, "Tolerante, requiere buen drenaje"),
      pref("Arenoso", 0.45, "Baja retención"),
      pref("Orgánico", 0.6, "Aceptable"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 2400,
    baseTemperature: 12,
    frostTolerance: 0.0,
    goodCompanions: ["Sorgo", "Crotalaria"],
    badCompanions: ["Okra"],
    followCrops: ["Trigo", "Cebada", "Arveja"],
    pestResistance: 0.2,
    mycorrhizalDependency: 0.5,
    description: "Fibra textil de origen vegetal. Ciclo largo, requiere temperaturas cálidas constantes.",
    agroecologicalNotes: "El algodón agroecológico utiliza control biológico de plagas (Trichogramma, Bacillus thuringiensis) y rotación con cultivos trampa. El cultivo de cobertura de crotalaria fija N y reduce nematodos.",
  },
  {
    id: "caña",
    name: "Caña de Azúcar",
    scientificName: "Saccharum officinarum",
    family: "Poaceae",
    category: "Industrial",
    habit: "Perenne",
    icon: "🎋",
    baseYield: 70000,
    maxYield: 100000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.05,
    fixedCostPerHa: 1200,
    kcInit: 0.5,
    kcMid: 1.25,
    kcEnd: 0.75,
    seasonDays: 365,
    idealIrrigationPct: 80,
    droughtTolerance: 0.4,
    waterloggingTolerance: 0.5,
    rootingDepth: "Profunda",
    nitrogenDemand: 140,
    phosphorusDemand: 60,
    potassiumDemand: 200,
    calciumDemand: 50,
    magnesiumDemand: 30,
    nitrogenFixer: false,
    idealPhMin: 5.5,
    idealPhMax: 7.0,
    saltTolerance: 0.55,
    soilPreferences: [
      pref("Franco-Limoso", 1.0, "Ideal para caña de azúcar"),
      pref("Franco", 0.95, "Excelente productividad"),
      pref("Franco-Arcilloso", 0.9, "Buena retención, alto potencial"),
      pref("Limoso", 0.85, "Fértil, productivo"),
      pref("Arcilloso", 0.75, "Tolerante a cierto encharcamiento"),
      pref("Franco-Arenoso", 0.65, "Requiere mayores aportes de agua"),
      pref("Orgánico", 0.7, "Alta fertilidad"),
      pref("Arenoso", 0.35, "Bajo potencial"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 3000,
    baseTemperature: 12,
    frostTolerance: 0.0,
    goodCompanions: ["Crotalaria", "Poroto caupí"],
    badCompanions: [],
    followCrops: ["Maíz", "Soja"],
    pestResistance: 0.3,
    mycorrhizalDependency: 0.4,
    description: "Gramínea perenne para producción de azúcar y etanol. Alta demanda hídrica y de K.",
    agroecologicalNotes: "La caña orgánica evita la quema previa a la cosecha, conservando la MO del suelo. La vinaza (subproducto) es un excelente fertilizante potásico. El cultivo intercalar de leguminosas fija N entre surcos.",
  },

  // =========================================
  //  AROMÁTICAS
  // =========================================
  {
    id: "lavanda",
    name: "Lavanda",
    scientificName: "Lavandula angustifolia",
    family: "Lamiaceae",
    category: "Aromática",
    habit: "Perenne",
    icon: "💜",
    baseYield: 4000,
    maxYield: 7000,
    yieldUnit: "kg/ha",
    pricePerKg: 3.5,
    fixedCostPerHa: 1500,
    kcInit: 0.4,
    kcMid: 0.6,
    kcEnd: 0.5,
    seasonDays: 250,
    idealIrrigationPct: 35,
    droughtTolerance: 0.85,
    waterloggingTolerance: 0.1,
    rootingDepth: "Profunda",
    nitrogenDemand: 40,
    phosphorusDemand: 25,
    potassiumDemand: 70,
    calciumDemand: 40,
    magnesiumDemand: 14,
    nitrogenFixer: false,
    idealPhMin: 6.5,
    idealPhMax: 8.0,
    saltTolerance: 0.3,
    soilPreferences: [
      pref("Franco-Arenoso", 1.0, "Ideal: drenante, alcalino, baja fertilidad"),
      pref("Arenoso", 0.95, "Excelente drenaje, mayor concentración de aceites"),
      pref("Franco", 0.8, "Bueno pero controlar humedad"),
      pref("Franco-Limoso", 0.65, "Riesgo de exceso de humedad"),
      pref("Limoso", 0.5, "No recomendado"),
      pref("Franco-Arcilloso", 0.45, "Pobre drenaje"),
      pref("Arcilloso", 0.2, "No apto"),
      pref("Orgánico", 0.55, "Fértil pero riesgo de poca floración"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1400,
    baseTemperature: 5,
    frostTolerance: 0.5,
    goodCompanions: ["Romero", "Tomillo", "Salvia"],
    badCompanions: ["Menta"],
    followCrops: [],
    pestResistance: 0.7,
    mycorrhizalDependency: 0.5,
    description: "Aromática perenne, aceites esenciales. Prospera en suelos pobres, bien drenados, alcalinos.",
    agroecologicalNotes: "La lavanda atrae polinizadores nativos y controladores biológicos. Ideal para bordes de cultivos. No requiere fertilización nitrogenada alta. El stress hídrico moderado mejora la concentración de aceites esenciales.",
  },
  {
    id: "menta",
    name: "Menta",
    scientificName: "Mentha × piperita",
    family: "Lamiaceae",
    category: "Aromática",
    habit: "Perenne",
    icon: "🌿",
    baseYield: 8000,
    maxYield: 14000,
    yieldUnit: "kg/ha",
    pricePerKg: 1.8,
    fixedCostPerHa: 1000,
    kcInit: 0.6,
    kcMid: 1.0,
    kcEnd: 0.9,
    seasonDays: 180,
    idealIrrigationPct: 75,
    droughtTolerance: 0.2,
    waterloggingTolerance: 0.5,
    rootingDepth: "Superficial",
    nitrogenDemand: 100,
    phosphorusDemand: 40,
    potassiumDemand: 120,
    calciumDemand: 35,
    magnesiumDemand: 20,
    nitrogenFixer: false,
    idealPhMin: 6.0,
    idealPhMax: 7.0,
    saltTolerance: 0.3,
    soilPreferences: [
      pref("Franco", 1.0, "Ideal: fértil y húmedo"),
      pref("Franco-Limoso", 0.95, "Fértil, buena retención"),
      pref("Franco-Arcilloso", 0.85, "Buena retención"),
      pref("Limoso", 0.8, "Alta fertilidad"),
      pref("Orgánico", 0.9, "Excelente en suelos orgánicos húmedos"),
      pref("Franco-Arenoso", 0.7, "Requiere riego frecuente"),
      pref("Arcilloso", 0.6, "Tolerante"),
      pref("Arenoso", 0.4, "Estrés hídrico frecuente"),
    ],
    idealSeasons: ["Primavera-Verano"],
    gddRequirement: 1200,
    baseTemperature: 8,
    frostTolerance: 0.6,
    goodCompanions: ["Repollo", "Tomate"],
    badCompanions: ["Manzanilla", "Lavanda"],
    followCrops: [],
    pestResistance: 0.55,
    mycorrhizalDependency: 0.4,
    description: "Aromática perenne rizomatosa. Se propaga por estolones. Prefiere suelos húmedos y fértiles.",
    agroecologicalNotes: "Es invasiva, ideal para bordes de cultivos o contenedores enterrados. Atrae abejas y controladores biológicos. El corte frecuente estimula el rebrote y la producción de aceite esencial.",
  },

  // =========================================
  //  FORESTAL
  // =========================================
  {
    id: "eucalipto",
    name: "Eucalipto",
    scientificName: "Eucalyptus grandis",
    family: "Myrtaceae",
    category: "Forestal",
    habit: "Perenne",
    icon: "🌳",
    baseYield: 20000,
    maxYield: 35000,
    yieldUnit: "kg/ha",
    pricePerKg: 0.08,
    fixedCostPerHa: 1500,
    kcInit: 0.5,
    kcMid: 1.0,
    kcEnd: 0.8,
    seasonDays: 365,
    idealIrrigationPct: 60,
    droughtTolerance: 0.6,
    waterloggingTolerance: 0.3,
    rootingDepth: "Profunda",
    nitrogenDemand: 60,
    phosphorusDemand: 25,
    potassiumDemand: 80,
    calciumDemand: 40,
    magnesiumDemand: 18,
    nitrogenFixer: false,
    idealPhMin: 5.5,
    idealPhMax: 7.0,
    saltTolerance: 0.4,
    soilPreferences: [
      pref("Franco-Arenoso", 1.0, "Ideal para crecimiento rápido"),
      pref("Franco", 0.95, "Excelente desarrollo"),
      pref("Arenoso", 0.9, "Buena adaptación suelos pobres"),
      pref("Franco-Limoso", 0.85, "Alta productividad"),
      pref("Limoso", 0.7, "Potencial medio-alto"),
      pref("Franco-Arcilloso", 0.7, "Aceptable"),
      pref("Arcilloso", 0.5, "Puede limitar el crecimiento radicular"),
      pref("Orgánico", 0.7, "Buena respuesta"),
    ],
    idealSeasons: ["Todo el año"],
    gddRequirement: 2000,
    baseTemperature: 8,
    frostTolerance: 0.2,
    goodCompanions: ["Pino", "Acacia"],
    badCompanions: [],
    followCrops: [],
    pestResistance: 0.5,
    mycorrhizalDependency: 0.6,
    description: "Forestal de crecimiento rápido para madera, celulosa y aceites esenciales.",
    agroecologicalNotes: "El eucalipto en sistemas silvopastoriles aporta sombra al ganado y madera. Asociar con leguminosas arbóreas (Acacia) mejora la fertilidad del suelo. Sus hojas tienen propiedades alelopáticas que reducen malezas.",
  },
];

// ═══════════════════════════════════════════════
//  HELPERS
// ═══════════════════════════════════════════════

export function getCropById(id: string): CropProperties | undefined {
  return CROP_DATA.find((c) => c.id === id);
}

export function getSoilById(id: SoilTexture): SoilProperties | undefined {
  return SOIL_DATA[id];
}

export const CROP_CATEGORIES: { label: string; key: string }[] = [
  { label: "Todos", key: "todos" },
  { label: "Cereales", key: "Cereal" },
  { label: "Oleaginosas", key: "Oleaginosa" },
  { label: "Legumbres", key: "Legumbre" },
  { label: "Hortícolas", key: "Hortícola" },
  { label: "Forrajeras", key: "Forrajera" },
  { label: "Frutales", key: "Frutal" },
  { label: "Industriales", key: "Industrial" },
  { label: "Aromáticas", key: "Aromática" },
  { label: "Forestales", key: "Forestal" },
];
